### ISSUE TITLE
[META] IntAcct API extension

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/apply-app#1]
This story is part of epic https://github.com/HyphaApp/hypha/issues/2352.

If possible keep all IntAcct API calls in a separate app that will only exist on the OTF install.

1. When Vendor is created/updated https://github.com/HyphaApp/hypha/issues/2379, do an API call and create/update the vendor in IntAcct. The IntAcct vendor_id will need to be saved in Hypha.
2. Via a (twice?) daily cron job update the vendor status for non active (pending) vendor. An active vendor has one or more contract attached in IntAcct.
3. When PM/staff view an invoice do an API call to IntAcct to retrieve the contract/deliverables and list them so the PM/staff can select one or more of them to be included in the invoice. There might be more then one contract so PM/Staff need to be able to pick the right one and see the correct deliverables.
4. When invoice is approved by Finance, do an API call and create it in IntAcct.
5. Via a (twice?) daily cron job update the invoice status (pending/approved/paid) for non paid invoices via API call to IntAcct.

**Comment by frjo** [comment]
@Parbhat Is it possible to keep the API calls in a separate app do you think?

I would like to have the core functionality of project/vendor/invoice etc in core Hypha. But the use of IntAcct is OTF only. Other organisation will most likely use other services, or just do it manually.

Best case is that other orgs can look at this IntAcct app and use it as a guide to build integration with all kinds of financial services. Reset will start using bill.com e.g.

**Comment by Parbhat** [comment]
@frjo We can keep the logic of making API calls in a separate app but will probably have to invoke them from the core functionality. How we will be making API calls to these services via Cron Jobs or it could be during user requests as well? If the common functionality is the same like creating vendors, invoices and payments etc for every organisation like OTF and Reset, we may keep the code for third party financial products like Sage Intacct and bill.com in Hypha core. So other organisations can also use it, we can provide an option to select financial products they want to use. But for this, the requirements should be the same for each organisation and these financial products provide the same functionality through their API. In case there are different requirements for organisation like how they want to process invoices, a different workflow then it would be good to keep the common functionality in core and custom in their respective forks. I will also go through the projects part of codebase as have not worked with it before.

**Comment by Parbhat** [comment]
A related query: How we are envisioning using these services? Will be replicate each and every action that current accounts person perform from Sage Intacct or bill dashboard? Or The goal is to sync data between the app and these services. For example, 1. Creating vendors in our app, API call will create it in IntAcct 2. Payments will be made from the IntAcct and we will sync the status in our app by calling the API.

**Comment by frjo** [comment]
@Parbhat I like your idea about keeping all the service integration in Hypha and letting each organisation turn them on/off as needed. API keys can be set as ENV vars etc.

**Comment by sks444** [comment]
@frjo, would it be possible for me to have top level entity access at Sage IntAcct sandbox dashboard?

Not sure if I would use it very frequently..but would be good to have in case I need to do some configurations myself. I guess it wouldn't be an issue, if not feasible.

In meantime, we would need to have [Web service authorizations](https://www.intacct.com/ia/docs/en_US/help_action/Company/Company_setup/Company_Information/Security/company-web-services-authorizations.htm?cshid=Web_services_authorizations). I can't find the option to add it(maybe because of the permissions). We need `senderID` and `senderPassword`.

I added a [webservices user](https://www-p02.intacct.com/ia/acct/frameset.phtml?.sess=7SnJHCFPmzLWl0xRm0XKIB-iMteXKQ..&.asx=opentechfund-sandbox%7Cdev-sks)(userID: sks) which will be used together with sender credentials to make request to the APIs.

Reference to the Prerequisites requirements: https://developer.intacct.com/web-services/#requirements

**Comment by frjo** [comment]
@sks444 You should have top level access now. Let me know if it did not take.

I have added the webservices user(userID: sks) to the list of "Web Services authorizations". I think you now should be able to use "sks" as senderID and the password for that account as senderPassword. 

(It was not easy to find the "Web Services authorizations", but found this article https://intercom.help/dryrun/en/articles/3642459-sage-intacct-and-dryrun-authorize-web-services )

**Comment by sks444** [comment]
Thanks @frjo!

I still seem to not have the top level access. Clicking on the top level entity logs me out of the dashboard.

Did you get any email regarding sender credentials after adding them in the list? If yes, can you forward that to my remoteinning email.

Webservices sender credentials and webservices user credentials, seem to be two different entities. Both of them are required to make the API calls.

**Comment by sks444** [comment]
Or maybe we need to contact Sage Intacct for the senderPassword.

> Sender ID and password are your API gateway credentials, one level above your company credentials. Only Sage Intacct can issue these to you. Contact Sage Intacct support or your account manager at Sage Intacct for more details.

> https://cdn.cdata.com/help/CTF/jdbc/RSBIntacct_p_SenderPassword.htm

>**Can I change the password for my Web Services sender ID?**
If you must change the password for a Web Services sender ID, open a case with Sage Intacct’s support team by logging in to the Sage Intacct Community.

We can contact Kathy about this.
