### ISSUE TITLE
Need distinction between content types in Activity Feed

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#15]
## User story
Different actions in the 'activity feed' tab all have the same colored tag. This makes it hard to scan the feed when looking for specific types of actions e.g. when looking for all payment requests it would be easier to spot them if they were tagged.

## Describe the solution you'd like in Hypha
Differentiate content types in Activity Feed

> Can you include a list of the different activity feed content-types in the above?

@ei8fdb here are examples. I'm also open to a different approach or closing this issue. This was a suggested ux/design...

- Approvals, e.g., Requested approval, Approved
- Action, e.g., Lead changed from Di to Bernard Tyers, Submitted a report, Invoice created, Updated Invoice status to: Changes Requested
- Workflow status update, e.g., Progressed from Contracting to In Progress

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Ideal deadline**

January 2022

**Comment by ei8fdb** [comment]
Can you include a list of the different activity feed content-types in the above?
