### ISSUE TITLE
Please remove automatically moving concept notes from 'need screening' to 'internal review'

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#17]
Please do not work on this issue until #18 has been completed.

Currently concept notes are automatically moved from need screening to internal review when one reviewer is assigned. Please remove this automation.  

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Ideal deadline**

January 2022

**Comment by frjo** [comment]
This is now on test for testing.

**Comment by fourthletter** [comment]
I tested this submission https://test-apply.hypha.app/apply/submissions/482/, but it moved automatically after one review

Does this only apply to NEW submissions?

**Comment by frjo** [comment]
Was this issue not about moving after assigning staff to submissions?

**Comment by frjo** [comment]
I have updated the PR to stop transitions after reviews as well as after assignments now. It all on test now as well (in a few minuts after I write this).

**Comment by fourthletter** [comment]
Tack! Works like a charm 💯
