### ISSUE TITLE
Add files tab to project view

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#25]
The OTF finance user wants to use Hypha as the main place to **view** (this doesn't mean store) files related to an individual project. 

## Sub-issues
- https://github.com/HyphaApp/hypha/issues/2634

## UI Demo

https://user-images.githubusercontent.com/1899506/121543330-1d4c7b00-ca09-11eb-8266-8e5975ca8f5f.mp4

## UI Designs

In the files tab view they see all the files that have been uploaded to Hypha that are related to the project:
![4e - files view - all files](https://user-images.githubusercontent.com/1899506/121170748-eb46e780-c855-11eb-9800-b7517d6cb14f.png)

The file category dropdown options come from the different file upload fields in Hypha - 

The applicant uploads:
- their W8 or W9 file
- invoice files (stored on IntAcct, requested via API)

The internal fund users uploads:
- upload contracts

@frjo mentioned the file category can be stored as metadata, so we can provide this file category filter.

### Search for file
They can search for files with particular words in the file name, e.g. search for files with "invoice" in the name:
![4f - files view - search for invoices](https://user-images.githubusercontent.com/1899506/121201526-e2194300-c874-11eb-991d-a3ea4817c05c.png)

### Filter by file category

![4g - files view - filter for contracts](https://user-images.githubusercontent.com/1899506/121201602-efcec880-c874-11eb-89f1-95505ffbd13f.png)

#### Stored on Hypha
- contract
- W8/W9 file, OFAC and SAM check results (compliance related) 

#### Finance system
(OTF - IntAcct)
- invoices (initially stored on Hypha, until they are approved, then they are moved to IntAcct)

**Comment by fourthletter** [comment]
## What is the minimum the files tab tab do?
The files tab is a view for documents that has previously been uploaded.

## Where are documents uploaded?

Doc Type | Full Proposal/Submissions| Vendor Set-up | Supporting documents Upload  | Intacct 
------------ | ------------- | -------------| -------------| -------------
csv/resume | 1 | 
bios | 1| 
budgets |1 | 
w8/w9 forms |  |  1 |  | | 
 | contract |  |  |  1| | 
contract amendments |  |  |  1| | 
 |SAM|  |  | 1 | need to check the same version every time a payment is processed| 
 | OFAC |  |  | 1 |need to check the same version every time a payment is processed | 
 | SOW|  |  | 1 | | 
 | Sole Source |  |  | 1 | | 
 | PAF |  |  | 1 | | 
 | Bank details|  | 1 | 1| | 
 |Invoice|  |  |  | ongoing| 
 | Receipts |  |  |  |ongoing |

**Comment by fourthletter** [comment]
Discussed this feature with Fredrik on Monday, Jan 24 - ALL documents are currently presented on each funded project's user interface. Does not need to be in a separate tab. 

I agree with him.

**Comment by ei8fdb** [comment]
@fourthletter how should we progress with this?

**Comment by ei8fdb** [comment]
From discussion with Di yesterday she's asked to wait until May/June to take this up.

**Comment by fourthletter** [comment]
On March 2 WebApp PAF/Contract Design Check-in - OTF decided to store compliance documents (contract, tax forms, OFAC, and SAM) outside of Hypha.
