### ISSUE TITLE
Reviewers are automatically assigned to submissions

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#26]
Weird bug...

I submitted a few new submissions to test. These submissions automatically assigned reviewers in 'Need Screening' unprompted 

As secondary buggy thing is that the system selected Bernard and Tom Saunders again and again even though there are several AC reviewers associated with this fund. Does the system have a thing for UX designers?

Only submissions from this fund https://test-apply.hypha.app/admin/pages/921/edit/ were impacted -- maybe it's an edge case?
https://test-apply.hypha.app/apply/submissions/502/
https://test-apply.hypha.app/apply/submissions/500/
https://test-apply.hypha.app/apply/submissions/499/

This bug did NOT appear when I submitted applications to this fund https://test-apply.hypha.app/admin/pages/731/edit/
https://test-apply.hypha.app/apply/submissions/501/

Priority
Low

**Comment by frjo** [comment]
External (AC) reviewers that are selected on the Fund are automatically assigned to each new submission, that is how it is supposed to work.

**Comment by fourthletter** [comment]
I'm closing this issue because the behavior only appears on test. 

External (AC) reviewers should not be assigned at the 'Need Screening' workflow status. 
https://test-apply.hypha.app/apply/submissions/502/

**Comment by frjo** [comment]
External reviewers that are added to the Fund are automatically assigned to all submissions that are submitted for that Fund. This is how it has worked from day one.
