### ISSUE TITLE
month/day/year date format for determinatons

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#29]
**Describe alternatives you've considered**

Please change the DATE to this format **mm/dd/yyyy** 

Managers need this date for correspondence with applicants.

<img width="344" alt="Screen Shot 2021-12-06 at 8 23 46 PM" src="https://user-images.githubusercontent.com/20019656/144909046-94f79883-e7d0-40c6-9957-d5f216c0d5e2.png">

**Additional context**

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff

**Ideal deadline**
January 2022

**Comment by Erioldoesdesign** [comment]
In the interests of good documentation on issues - this was discussed on a standup call the week of the 13th of December re. the uses of 'fuzzy time' and 'non fuzzy time' as well as process and usefulness from both a user pov and organisational (OTF) pov.
