### ISSUE TITLE
Remote Apply Button on Website

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#32]
Could we please remove the 'apply' buttons from the website? We've changed our work flow, and no longer need this button.

<img width="873" alt="Screen Shot 2021-12-08 at 10 07 07 AM" src="https://user-images.githubusercontent.com/20019656/145180444-073ac4f3-7286-40fe-be7f-678ffb93b887.png">

**Comment by frjo** [comment]
Is it only the learning lab apply buttons or all of them that should be removed?

**Comment by frjo** [comment]
Temporary fix being deployed to live now. Should hopefully work but since the page is not live yet we can't test.

**Comment by fourthletter** [comment]
I tested and it looks great! Thank you so much.
