### ISSUE TITLE
Meta Terms Filter

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#37]
## User Story

fredrik will kill me for asking this, but I won't blame him. We need to put back the filter for meta terms. 

As a program manager I need to recommend an application to another lab. Meta terms is one approach we can use to make this association or linkage.

## What happens now?

Staff would write this in the notes or would have to search for applications manually. 

## Describe the solution you'd like in Hypha

We need to put back the filter for meta terms. OR Create a new dashboard because program managers are interested in learning more about which fund/lab an applicant has applied to.

**Comment by frjo** [comment]
Adding meta terms filter back is extremely simple. I just change the settings on OTF live site so they show up again.
