### ISSUE TITLE
Determination Forms

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#38]
## User Story

As a program manager I need to recommend an application to another lab. A **meta term** or **category question** in the determination template form is one approach we can use to make this association or linkage.

There is functionality for the user to add determination message templates but those templates are not imported when the user creates a determination for an application. 

## Describe the solution you'd like in Hypha

1. Create determination template messages.
2. Add a determination to an application.

**Priority**

- Medium priority 

**Affected roles**

- Staff
- Applicant

**Additional context**
Related to GH issue [#2463](https://github.com/HyphaApp/hypha/pull/2463)

**Comment by frjo** [comment]
Meta terms and category questions have nothing to do with determination messages templates.

This seems like two separate issues.

Determination message templates was implemented once upon a time. It was not working like OTF wanted so we disabled them until we could get a fix done. We have now rebuilt determination forms in to stream fields (so staff can edit and add them just like application and review forms). The functionality therefor needs to be rebuilt a bit as well.

Definitely something we should get done, I think many Hypha using organisations would like this functionality.
