### ISSUE TITLE
Revise display of previous submissions associated with the application

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#39]
## User Story
As a Program Manager or an applicant I would like to view previous submissions associated with the application.

This would help program managers better understand the types of support an applicant has received in the past. For example, has the project receive usability, ux, security audit, rapid response support in the past?

## What happens now?
Previous submissions associated with an applicant are presented in the bottom right-hand corner. 

## What is the minimum the files tab in the Submissions tab should do?

- [ ] display applications that have been previously submitted by the applicant
- [ ] display **dates** when files were uploaded
- [ ] display type of **fund/lab**

## To be added later
Eventually the following should be added:
- [ ] filter
- [ ] sorting
- [ ] search
- [ ] include information about type of fund associated with the application
- [ ]  by applicants during the full proposal stage - e.g. cvs/bios/budgets/

**Priority**
- Low

**Affected roles**

- Staff
- Applicants

**Comment by frjo** [comment]
Past submissions and current uploaded files are two different things. I do not see how we can add them in one table and make it useable.

I do not see how moving them to (hiding them in) another tab makes them easier to find, rather the opposite.
