### ISSUE TITLE
Change Meta Terms function to allow multiple selection

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#42]
### User Story

As a user I would need to associated more than one meta term to an application.  Example: 'https://test-apply.hypha.app/apply/submissions/426/'

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Screenshots/Gif 🍿**

![Kapture 2022-01-24 Meta Terms](https://user-images.githubusercontent.com/20019656/150789601-5245e138-2b32-4bb2-b09c-b5d20c7f9d7c.gif)

**Desktop (please complete the following information):**

 - OS:  iO
 - Browser  Chrome
 - Version 12.1

**Comment by frjo** [comment]
You need to add them one by one but there is no problem adding as many as needed.

![Skärmavbild 2022-01-25 kl  13 16 59](https://user-images.githubusercontent.com/191392/150975506-39ee1ec3-36ea-44d6-a0d7-0a62d1d64585.png)
