### ISSUE TITLE
Please remove 'Current project status' from Projects We Support page

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#61]
Please remove 'Current project status' from Projects We Support page.

![Screen Shot 2022-04-04 at 11 52 57 AM](https://user-images.githubusercontent.com/20019656/161847090-0539d93f-5e5e-4fa4-81f7-472d264fd98a.png)

**Comment by fourthletter** [comment]
@frjo The release of this feature may have been lost in the shuffle. This section still appears on the website.

**Comment by frjo** [comment]
@fourthletter Can you post a URL where you see it?

**Comment by fourthletter** [comment]
Cloudflare issue, will clear it up and update will show. Thank you!
