### ISSUE TITLE
Enforce 2FA for all user groups

### ISSUE THREAD

**Issue by Techslammer** [OpenTechFund/apply-app#62]
**Describe Feature Request**

Currently, 2FA is only enforced for the staff user group (via Google login). This request is for it to apply to all user groups and block users who do not have it unabled.

**Requested solution**

- Block access to Hypha if user does not have 2FA enabled.
- Reset password for that user
- User resets password and sets up 2FA in order to access
- Add a setting to turn this on/off. Default will be off so it works just like now. OTF will have it set to on.

**Priority**

- High 

**Affected roles**
- Applicants
- Reviewers
- Partners
- Developers
- General public

**Ideal deadline**
April 18th

**Comment by fourthletter** [comment]
## Description

All user accounts without 2FA will be forced to set up 2FA and reset their passwords when logging into the WebApp.

## Possible workflows

- All users without 2FA will be prompted with instructions for how to set up 2FA and reset their password during log-in. 

## What is required?

design: the process for a user to create 2FA when logging into the WebApp
technical: to figure out how to remove access to all users without 2FA, and implement 2FA setup on the log-on page. 

## Current login Page

![image](https://user-images.githubusercontent.com/20019656/162276825-2ee61f5d-1748-49cc-9942-5ade730e5f67.png)

**Comment by frjo** [comment]
@sandeepsajan0 @sks444  Maybe we can make good use of the class `OTPRequiredMixin`. We might need a intermediate class that checks a new setting, something like `TWO_FACTOR_ENFORCE`

It would need to be added to a lot of views but otherwise seems simple and straightforward. I like the resulting flow for users and we do not need to force them to reset their passwords etc.

See https://django-two-factor-auth.readthedocs.io/en/stable/class-reference.html?highlight=OTPRequiredMixin#two_factor.views.mixins.OTPRequiredMixin

This is how it looks by default if you visit a view with `OTPRequiredMixin` without having 2FA setup on your account.

![Skärmavbild 2022-04-08 kl  08 36 40](https://user-images.githubusercontent.com/191392/162378619-07fce7ac-4cda-4217-8f6c-081f4e08bc77.png)

**Comment by Erioldoesdesign** [comment]
'Enforce' is probably not the best language to use with a high risk group that might have bad experiences with the word and institutions that are 'enforcers' recommend language like 'OTF/This system needs you to verify your account in order both us and yourself to stay safe and secure. Enabling two-factor auth takes approximately x time and needs you to have access to an authenticator app etc..'

^ not perfect UX language but lets make sure we're offer help to folks not used to this process as much as the folks that do this all the time.

Also just a quick question, do you have plans for how to support applicants that might only be on feature phones?

**Comment by fourthletter** [comment]
During standup April 11 developers discussed:

## Description

When a user logs into Hypha, they will be redirected to setup their 2fa

## Proposed solution 

Develop middleware for all requests and from any url

- [ ] Allow users to log-in without requirement to change password
- [ ] Users will be directed to a message asking them to setup 2fa
- [ ] After log-in, users will be directed to another screen to setup 2fa
- [ ] Users could be redirected to their dashboard after 2fa setup has been completed
- [ ] Default for this setting is OFF as not all adopters will wish to enact 2fa requirement

**Comment by fourthletter** [comment]
> Also just a quick question, do you have plans for how to support applicants that might only be on feature phones?

Hi @Erioldoesdesign - thank you for the input. I updated the [original GH issue ](https://github.com/OpenTechFund/apply-app/issues/62#issuecomment-1092097956 )with workflows to accommodate different types of users, including those with feature phones.

**Comment by fourthletter** [comment]
April 12 standup notes

- Sandeep demo new functionalties and potential bypasses
- We will need to test for SSO to better understand how they would be impacted - these users should be verified via middleware, but we will check
- feature ready for test this week

**Comment by fourthletter** [comment]
@ei8fdb 

April 13 - notes

- [ ] Create test cases for what we expect to happen when implementing 2fa. We will follow these test cases when we test functionalities for quality assurance. Example test cases: someone lost their mobile, new applicant unfamiliar with 2fa
- [ ] Conduct 30 minute UX session to gather input and experience from program specialists
- [ ] Post-implementation design fixes

**Comment by Erioldoesdesign** [comment]
Did a quick little user journey test walk through - will upload screenshots with thoughts later today but none are blockers/critical issues to stop whats on test being live - Great work product + dev team 😄

**Comment by fourthletter** [comment]
QA

Applicant
- [ ] sees setup page after login
- [ ] could access setup page and see backup codes
- [ ] has instructions for setup and prompt for saving backup codes
- [ ] message on their mobile is clear/present 

Reviewer
- [ ] sees setup page after login
- [ ] could access setup page and see backup codes
- [ ] has instructions for setup and prompt for saving backup codes
- [ ] message on their mobile is clear/present 

Partner
- [ ] sees setup page after login
- [ ] could access setup page and see backup codes
- [ ] has instructions for setup and prompt for saving backup codes
- [ ] message on their mobile is clear/present

**Comment by fourthletter** [comment]
Standup April 21

### Meeting Notes
- [x] User research with OTF staff
- [x] BT presented workflow for users, suggested changes to the user interface to streamline process
- [ ] BT will update workflow based on feedback from developers during technical review

### Challenge
Users without smartphones (authentication app) will not be able to generate backup codes. PM needs to ruminate on security risks of sending code via email for applicants without smart phones.

**Comment by fourthletter** [comment]
Standup April 26

When we push this feature upstream to Hypha Core, the default is either global or enable for specific users roles.

**Comment by frjo** [comment]
No, if 2FA enforce is set to "on" is is active for all users regardless of roles. Users logging in via Google auth is exempt however.
