### ISSUE TITLE
Giver Staff Admin role permission to disable 2fa on user accounts

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#65]
## Description

As a staff admin, I need the capacity to disable 2fa on user accounts to better manage users' access to the platform. The staff admin role overseas user accounts and troubleshoot technical glitches via the WagTail admin in Hypha. 

## Solution

Staff admin role has permission to disable 2fa for all user accounts except for Admin

**Comment by ei8fdb** [comment]
From research into 2FA management processes, these are the 2 workflows I've seen:

## 1. Disable 2FA for user affected
![Screenshot 2022-04-26 at 13 45 59](https://user-images.githubusercontent.com/1899506/165293084-781d9712-bb1a-43de-b28e-31b3fb0694ab.png)

Possible design approach [documented in Miro board](https://miro.com/app/board/uXjVO8_szdM=/?moveToWidget=3458764524024014367&cot=14). 

## 2. Generate TOTP code for user affected
![Screenshot 2022-04-26 at 13 47 12](https://user-images.githubusercontent.com/1899506/165293287-85e56ad2-b4ae-4683-bd39-27fd5ba0d42d.png)

Possible design approach [documented in Miro board](https://miro.com/app/board/uXjVO8_szdM=/?moveToWidget=3458764524028179328&cot=14).
