### ISSUE TITLE
How would you like configurable UX settings to be implemented?

### ISSUE THREAD

**Issue by slifty** [OpenTechFund/apply-app#68]
There are a series of UX changes that we have in mind for our Hypha instance; I could simply make the changes in the templates, but would like to avoid diverging too far from origin.  This means I'd rather implement this as configurable elements.

Just as an example: we don't want the "Apply" button to appear at the bottom of the home page.  There will also soon be a desire to change which sections appear in the application review.

I could see this done in a few ways:

1. Adding settings to `base.py` (so it can be configured via `local.py` or environment variable)
2. Adding settings to the wagtail admin (so it can be configured by an admin)

What do you all think, and is this kind of configuration something you would like to see added to the project?

**Comment by frjo** [comment]
Settings that it is likely staff need to change from time to time we normally put in Wagtail admin.

If the settings are something you set once, if they have important side effects etc. we put them in the settings file.

I think many UX changes that are more cosmetic could be good to have in Wagtail admin.

P.S. Better to post issue to main Hypha repo at https://github.com/HyphaApp/hypha/issues

**Comment by slifty** [comment]
Oh whoops -- I'm sorry for posting this here that was a misfire!

Thanks for the answer; I'll close the issue!
