### ISSUE TITLE
Update automated email for NEW applicants

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/apply-app#70]
This automated email was sent to a NEW applicant submitting a submission for the first time with this account. They should have received an email asking them to setup a password.

> On May 11, 2022, at 2:23 PM, app@apply.opentech.fund wrote:
> 
> 
> Dear [applicant],
> 
> 
> We appreciate your Internet Freedom Fund application submission to the Open Technology Fund. We will review and reply to your submission as quickly as possible.
> 
> Our reply will have the next steps for your Internet Freedom Fund application. You can find more information about our support options, review process and selection criteria on our website.
> 
> We are asking all applicants to please enable two-factor authentication for your account on OTF’s application platform. You can create or change your 2FA account by clicking on your name on the upper right hand corner. This will lead you to your personal profile. You will see the option to update your account security. Here is additional information on how to set up your 2FA in the Applicant’s Guidebook https://guide.opentech.fund/application-platform-guidance/login/two-factor-authentication-2fa
> 
> Project name:
> Contact name: 
> Contact email: 
> 
> Kind Regards,
> The OTF Team
> 
> --
> Open Technology Fund
> 
>

**Comment by frjo** [comment]
This e-mail is sent out for each new submission. If the applicant has applied before or not makes no difference.
